services:
  - type: web
    name: ngl-clone
    env: python
    plan: starter
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    healthCheckPath: "/"
